### PR TITLE
Get travis running against latest python and django versions.

### PR DESCRIPTION
**Pull request by troygrosfield**
The pull request has been merged for django 1.7:

- https://github.com/batiste/django-page-cms/commit/721efd74545767fecc596f23c12569073e6e192f

Now, need to get the test suite running against latest django and latest python.

### CODE REVIEW

**Comment by troygrosfield** [comment]
Tests are correctly passing for latest django + python combo.  However, the tests are failing for django 1.6:

- https://travis-ci.org/batiste/django-page-cms/jobs/56156261

```
$ python pages/test_runner.py
Traceback (most recent call last):
  File "pages/test_runner.py", line 15, in <module>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
```
``django.setup()`` was introduced in django 1.7 [1].  If support is dropped for django 1.6 then that's fine with me as I'm on django 1.7, python 3.4.  However, the .travis.yml file and docs should be update to reflect that.

[1] https://docs.djangoproject.com/en/1.7/ref/applications/

**Comment by batiste** [comment]
I personally have very little incentive to maintain the CMS for 1.6. So I will probably update the documentation before releasing a new package.

Thanks for pointing that problem out.

**Comment by batiste** [comment]
I just released a new version of the CMS https://pypi.python.org/pypi/django-page-cms

This version only works with the latest 1.8 version.
