### ISSUE TITLE
Css and jquery broken on django 2.2

### ISSUE THREAD

**Issue by scwall** [batiste/django-page-cms#199]
Hi, I am migrating an old project from django 1.6 to version 2.2. I have been gradually moving up the versions and currently django page cms is not working on django 2.2 . There are problems with the distribution of static files.
The other static files of the other modules seem to be well distributed in the administration part though
```
RelatedObjectLookups.js:149 Uncaught TypeError: $(...).on is not a function
    at HTMLDocument.<anonymous> (RelatedObjectLookups.js:149)
    at Function.<anonymous> (jquery.js:19)
    at Function.each (jquery.js:12)
    at Function.ready (jquery.js:19)
    at HTMLDocument.<anonymous> (jquery.js:19)
(anonymes) @ RelatedObjectLookups.js:149
(anonymes) @ jquery.js:19
each @ jquery.js:12
ready @ jquery.js:19
(anonymes) @ jquery.js:19
jquery.js:4055 Uncaught ReferenceError: page_media_url is not defined
    at HTMLDocument.<anonymous> (pages_form.js:26)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)
(anonymes) @ pages_form.js:26
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
jQuery.readyException @ jquery.js:4054
(anonymes) @ jquery.js:4074
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
process @ jquery.js:3850
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
jquery.rte.js:30 GET http://localhost.test:8000/site_media/static/pages/ net::ERR_ABORTED 404 (Not Found)
tryEnableDesignMode @ jquery.rte.js:30
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
bold.gif:1 GET http://localhost.test:8000/site_media/bold.gif 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
italic.gif:1 GET http://localhost.test:8000/site_media/italic.gif 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
unordered.gif:1 GET http://localhost.test:8000/site_media/unordered.gif 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
image.png:1 GET http://localhost.test:8000/site_media/image.png 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
link.png:1 GET http://localhost.test:8000/site_media/link.png 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
close.gif:1 GET http://localhost.test:8000/site_media/close.gif 404 (Not Found)
Image (asynchrone)
buildFragment @ jquery.js:5032
jQuery.parseHTML @ jquery.js:10337
jQuery.fn.init @ jquery.js:3167
jQuery @ jquery.js:157
toolbar @ jquery.rte.js:104
(anonymes) @ jquery.rte.js:77
tryEnableDesignMode @ jquery.rte.js:43
enableDesignMode @ jquery.rte.js:75
(anonymes) @ jquery.rte.js:15
each @ jquery.js:381
each @ jquery.js:203
jQuery.fn.rte @ jquery.rte.js:13
(anonymes) @ ?language=&:500
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (asynchrone)
(anonymes) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
jquery.rte.js:30 GET http://localhost.test:8000/site_media/static/pages/ net::ERR_ABORTED 404 (Not Found)
```
thank's in advance :)
